#!/bin/bash
# If the compilation of Nmag fails on your system, you are encouraged to use
# this script to generate a bug report, which may help the Nmag developers to
# understand the bug and fix it. Use it in this way:
#
#   cd nmag-0.1 # enter the directory where your Nmag distribution is 
#   ./build-bug-report
#
# The command will create an archive (i.e. a file named bug-report.tgz)
# containing information about the status of the compilation of Nmag, plus some
# details about your system (processor type, distribution, etc).
# You should send this file by mail to the Nmag developers, if you want them to
# help you with it.

NMAGROOT=.
BUGREPORT=$NMAGROOT/bug-report
PROBLEMS=$BUGREPORT/problems

if [ -d $BUGREPORT ]; then
  echo "Remove (or rename) the directory $BUGREPORT before proceeding."
  exit 1
fi

echo "Creating temporary directory to collect debug information"
mkdir $BUGREPORT

# Take not of what has been built
echo "Getting dependency status"
(cd $NMAGROOT && ls -l --sort=time .deps*) >> $BUGREPORT/deps

function myls {
  echo ls -l $* >> $BUGREPORT/libs
  ls -l $* >> $BUGREPORT/libs
}

# Take note of the files which have been generated
# (useful to see that all shared libraries have been generated)
echo "Getting content of pkgs and lib directories"
myls $NMAGROOT/pkgs
myls $NMAGROOT/hlib-pkg
myls $NMAGROOT/lib
myls $NMAGROOT/lib/petsc/lib
myls $NMAGROOT/lib/mpich2/lib
myls $NMAGROOT/nsim/interface/extra/lib

# See what libraries the Nsim executable is actually linking to
# (useful to see if there are some linking problems or conflicts between libs)
echo "Getting ldd for nsim executable"
NSIM_EXEC=$NMAGROOT/nsim/src/nsimexec
if [ -x $NSIM_EXEC ]; then
  (. $NMAGROOT/exports.bash && ldd $NSIM_EXEC) \
      >> $BUGREPORT/nsim.ldd
else
  echo "Nsim executable ($NSIM_EXEC) not found"
  echo "Nsim executable ($NSIM_EXEC) not found" >> $PROBLEMS
fi

# The output of nm should show some lindholm functions (the ones in the patch)
echo "Getting content of HLib library (if present)"
HLIB_LIBHMATRIX=$NMAGROOT/nsim/interface/extra/lib/libhmatrix-1.3.so
if [ -f $HLIB_LIBHMATRIX ]; then
  nm $HLIB_LIBHMATRIX > $BUGREPORT/libhmatrix.nm
else
  echo "HLib library ($HLIB_LIBHMATRIX) not found"
  echo "HLib library ($HLIB_LIBHMATRIX) not found" >> $PROBLEMS
fi

# Copy the logs and other useful files
echo "Getting nsim configuration and compilation logs"
FILES="export_paths.sh exports.bash set_petsc_arch.sh nsim/bin/ldflags.bash \
       nsim/config/configuration.inc nsim/bin/ldflags.bash Makefile \
       hdf5/config.log lib/petsc/configure.log mpich2/config.log \
       python/config.log sundials/config.log gsl/config.log hlib/config.log \
       nsim/compilation.log qhull/config.log"

for FILE in $FILES; do
  INFILE=$NMAGROOT/$FILE
  FILENAME=`echo $FILE | tr / _`
  OUTFILE=$BUGREPORT/$FILENAME

  if [ -f $INFILE ]; then
    echo "  Including in bug report: $INFILE --> $OUTFILE."
    cp $INFILE $OUTFILE

  else
    echo "  File $INFILE not found."
    echo "File $INFILE not found." >> $PROBLEMS
  fi
done

# Get a copy of the environment variables
echo "Getting environment variables"
export > $BUGREPORT/environment

# Checking the executables we use
echo "Getting path to executables"
FILES="ocaml ocamlfind"
for FILE in $FILES; do
  SYSEXEC=`which $FILE`
  (. $NMAGROOT/exports.bash; OUREXEC=`which $FILE`; \
      echo "sys: $SYSEXEC, our: $OUREXEC") >> $BUGREPORT/which
done

# Now we start to get info about the machine: here the processor...
echo "Getting processor information"
cat /proc/cpuinfo >> $BUGREPORT/proc_cpuinfo

# Distribution, kernel and architecture...
echo "Getting system information"
cat /proc/version >> $BUGREPORT/proc_version
cat /etc/issue >> $BUGREPORT/etc_issue
uname -a >> $BUGREPORT/uname_a

# Finally we pack everything in one single file
echo "Building tar file with all the collected files"
tar czvf bug-report.tgz $BUGREPORT

echo "Removing temporary directory"
rm -rf $BUGREPORT

